### ISSUE TITLE
BE: Notifications framework for Sitters and Owners

### ISSUE THREAD

**Issue by dahrk** [hatchways/team-pine-cone#70]
Sitters should be notified if their services have been requested
Owners should be notified if their request was accepted/denied

This task encompasses the backend portion of storing new notifications and sending them to owners and sitters

**Comment by dproc96** [comment]
_(Notes for myself for when I'm building this)_
Potential Socket Scopes
- New message
- New request
- Updated request
- Paid request (part of updated? Maybe not because we may want to update a wallet component or similar down the road)

Since requests are already stored in the Profile, may make the most sense to handle socket interaction in the Profile Context provider on the Front End which would also make accessing the socket easier.

Notifications should be stored in the Profile Model as well so they persist even if the user does not have it open. Should we retain read notifications? I don't think there's a need for it.

Three branches for this and the Front-End portion:
- feature-notifications-integrated (should be based on Manage Bookings branch for ease of testing)
- feature-notifications-backend
- feature-notifications-frontend
